name: Trigger auto deployment for capp-snehapar-sample-repo1234

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capp-snehapar-sample-repo1234-AutoDeployTrigger-c0460ba4-9f5b-4673-a909-d9f819f78c86.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAPPSNEHAPARSAMPLEREPO1234_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.CAPPSNEHAPARSAMPLEREPO1234_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPSNEHAPARSAMPLEREPO1234_REGISTRY_PASSWORD }}
          containerAppName: capp-snehapar-sample-repo1234
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/capp-snehapar-sample-repo1234:${{ github.sha }}
          

     

