name: Trigger auto deployment for test-sample3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-sample3-AutoDeployTrigger-11a2064c-8f9e-4281-a03c-caed17c26d8e.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTSAMPLE3_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.TESTSAMPLE3_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTSAMPLE3_REGISTRY_PASSWORD }}
          containerAppName: test-sample3
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/test-sample3:${{ github.sha }}
          

     

