name: Trigger auto deployment for test-sample4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-sample4-AutoDeployTrigger-91b21248-cf1f-478e-80d6-f20cb37a7405.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTSAMPLE4_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: snehaparacr.azurecr.io
          registryUsername: ${{ secrets.TESTSAMPLE4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTSAMPLE4_REGISTRY_PASSWORD }}
          containerAppName: test-sample4
          resourceGroup: ca-snehapar-group
          imageToBuild: snehaparacr.azurecr.io/test-sample4:${{ github.sha }}
          

     

